Insouq.Web.Agency/Controllers/MotorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using insouq.Services.IServices;
using insouq.Services.IServices.Agency;
using insouq.Shared.DTOS;
using insouq.Shared.DTOS.Filters;
using insouq.Shared.Utility;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Insouq.Web.Agency.Controllers
{
    public class MotorsController : Controller
    {
        private readonly IAccountsService _accountService;
        private readonly IAgencyAccountService _agencyAccountService;
        private readonly IAgencyMotorsServices _AgencyMotorsService;
        private readonly IUsersService _usersService;
        private readonly IDropDownService _dropDownService;

        public MotorsController(IAccountsService accountService, IAgencyAccountService agencyAccountService, IAgencyMotorsServices agencyMotorsService, IUsersService usersService, IDropDownService dropDownService)
        {
            _accountService = accountService;
            _AgencyMotorsService = agencyMotorsService;
            _usersService = usersService;
            _dropDownService = dropDownService;
            _agencyAccountService = agencyAccountService;
        }

        private int getUserId()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claims = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            return Int32.Parse(claims.Value);
        }
        private async Task<insouq.Models.User> getUser()
        {
            var user = await _agencyAccountService.GetUserById(getUserId());
            return user;
        }
        private async Task<insouq.Models.Agent> getAgent()
        {
            var agent = await _agencyAccountService.GetAgentByUserId(getUserId());
            return agent;
        }

        public async Task<IActionResult> index()
        {
            ViewBag.phoneNumber = await _usersService.GetPhoneNumber(getUserId());
            var agency = await _agencyAccountService.GetAgencyByUserId(getUserId());
            //HttpContext.Session.SetObjectAsJson("agency", agency);
            HttpContext.Session.SetString("SessionAgencyName", agency.Name);
            var user = await getUser();
            HttpContext.Session.SetString("SessionAgencyPicture", user.ProfilePicture);
            var agent = await getAgent();
            HttpContext.Session.SetString("SessionMobileNumberWithCode", user.MobileNumber);
            HttpContext.Session.SetString("SessionWorkNumber", agent.WorkNumber);
            return View();
        }

        public ActionResult PostMotorsAd()
        {
            return View();
        }
        public async Task<IActionResult> Add(int categoryId)
        {
            //if (categoryId == 0)
            //{
            //    return RedirectToAction("Index", "Home");
            //}
            categoryId = 2;
            
            //HttpContext.Session.SetString("agencyName", agency.Name);
            var dto = new insouq.Shared.DTOS.AgencyDTOS.MotorsAdDTO
            {
                CategoryId = categoryId,
            };
            return View(dto);
        }

        //[HttpPost]
        //[AutoValidateAntiforgeryToken]
        //public async Task<IActionResult> AddInitalMotor(AddInitalMotor dto)
        //{
        //    var hostName = $"https://{this.Request.Host}";
        //    var response = await _motorsService.AddInitialMotor(getUserId(), dto, hostName);

        //    if (!response.IsSuccess)
        //    {
        //        ModelState.AddModelError(string.Empty, response.Message);
        //        return View(dto);
        //    }

        //    return RedirectToAction(nameof(Add), new { id = response.Id, categoryId = dto.CategoryId, });
        //}

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Add(insouq.Shared.DTOS.AgencyDTOS.MotorsAdDTO dto)
        {
            //if (!ModelState.IsValid)
            //{
            //    return View(dto);
            //}
            var hostName = $"https://{this.Request.Host}";
            var response = await _AgencyMotorsService.Add(getUserId(), dto, hostName);

            if (!response.IsSuccess)
            {
                ModelState.AddModelError(string.Empty, response.Message);
                return View(dto);
            }

            return RedirectToAction("PackagesSubsicription", "Ads");
        }



        public async Task<IActionResult> Update(int adId)
        {
            var ad = await _AgencyMotorsService.GetMotorAd(adId);

            if (ad == null)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(ad);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Update(UpdateMotorsDTO dto)
        {
            var hostName = $"https://{this.Request.Host}";
            var response = await _AgencyMotorsService.Update(getUserId(), dto, hostName);

            if (!response.IsSuccess)
            {
                ModelState.AddModelError(string.Empty, response.Message);
                return View(dto);
            }

            return RedirectToAction("Index", "Home");
        }


        [HttpPost]
        public async Task<IActionResult> FilterMotors([FromBody] MotorFilters dto)
        {
            var list = await _AgencyMotorsService.FilterMotors(dto);

            return PartialView("~/Views/Partials/_UserAd.cshtml", list);

        }

        public IActionResult GetData(int categoryId)
        {
            return PartialView("~/Views/Partials/_MotorData.cshtml", categoryId);
        }
    }
}

Insouq.Web.Agency/Views/Partials/_Agents.cshtml
@model System.Collections.Generic.List<insouq.Models.Agent>

<div>
    @*@using (Html.BeginForm("searchAgent", "LeftSideBar", FormMethod.Post))
    {*@
        <table class="agents-table" id="agentsTable">
            <tr>
                <th>NO</th>
                <th>Agent name</th>
                <th>Profile Picture</th>
                <th>Email Address</th>
                <th>Broker No.</th>
                <th>Mobile Number</th>
                <th>Agent Status</th>
                <th>Action</th>
            </tr>

            @{
                if (Model != null)
                {

                    foreach (var item in @Model)
                    {
                        
                        <tr class="featured-box1">
                            <td>@Html.DisplayFor(model => item.Id) </td>
                            <td>@Html.DisplayFor(model => item.Name)</td>
                            <td><img src="../image/@Html.DisplayFor(model=> item.Picture)" alt="user-img" width="36" class="img-circle profile-img-whidth2"></td>
                            <td>@Html.DisplayFor(model => item.Email)</td>
                            <td>@Html.DisplayFor(model => item.BrokerNo)</td>
                            <td>@Html.DisplayFor(model => item.MobileNumber)</td>
                            @{
                                if (item.Status == false)
                                {
                                    <td>
                                        <p><button type="button" class="ActiveAgent-btn" style="opacity: 50%;" onclick="ActiveAgent(@item.Id)">Active</button></p>
                                        <p><button type="button" class="dis-btn" id="btnDisableAgent" >Disable</button></p>
                                    </td>
                                }
                                else if (item.Status == true)
                                {
                                    <td>
                                        <p><button type="button" class="ActiveAgent-btn" id="btnActiveAgent">Active</button></p>
                                        <p><button type="button" class="dis-btn"  style="opacity: 50%; " onclick="DisableAgent(@item.Id)">Disable</button></p>
                                    </td>
                                }
                            }

                            <td>
                                <button type="submit" class="change-btn17" id="btnEdit"
                                        @*asp-controller="LeftSideBar" asp-action="EditAgentData" asp-route-adId="@item.Id"*@ onclick="window.location.href = ''">
                                    @*onclick="window.location.href = '/leftsidebar/editagent'" >*@
                                    <i class="fa fa-pencil icon-padding" aria-hidden="true"></i>Edit
                                </button>
                                <p>
                                    <button type="button" class="change-btn18" name="button" id="btnDelete" onclick="DeleteAgent(@item.Id)">
                                        <i class="fa fa-trash-o icon-padding" aria-hidden="true"></i>Delete
                                    </button>
                                </p>
                            </td>
                        </tr>
                    }
                }
            }
        </table>
                @*}*@
    </div>

Insouq.Web.Agency/Views/Partials/_UserAd.cshtml
@using insouq.Shared.Utility;
@using insouq.Services.IServices;
@using System.Security.Claims;

@inject IAdsService _adsService

@{
    var itemIndex = 1;

    string AddDoubleQuotes(string value)
    {
        return "\"" + value + "\"";
    }

    var itemsCount = Model.Count;

    var c = 1;
    var b = 0;
    var itemsPerPage = 0;

    if (itemsCount < 5)
    {
        itemsPerPage = itemsCount;

    }
}


@while (itemsCount > 0)
{
    var id = "pageItems" + c;

    var to = itemsPerPage;

    if (itemsPerPage == 0)
    {
        if (b + 5 > Model.Count)
        {
            to = Model.Count;
        }
        else
        {
            to = b + 5;
        }
    }

    var display = "none";

    if (c == 1)
    {
        display = "block";
    }

    @*<div class="pageAds" id="@id" style="display:@display">*@

    @for (int i = b; i < to; i++)
    {
        var item = Model[i];


        <div>

            <table>
                <tr>
                    <th>Status</th>
                    <th>Ref</th>
                    <th>Maker</th>
                    <th>Description</th>
                    <th>Location</th>
                    <th>Price</th>
                    <th>Year</th>
                    <th>Model</th>
                    <th>Agent</th>
                </tr>


                <tr>
                    <td><div class="green-circle"></div> </td>
                    @foreach (var picture in item.Pictures)
                        if (picture.MainPicture)
                        {
                            <td><img src="@picture.ImageURL"><p>@item.PostDate </p> </td>
                            break;
                        }
                    <td>@item.En_Maker</td>
                    <td>@item.Description</td>
                    <td>@item.En_Location</td>
                    <td>@item.Price</td>
                    <td>@item.Year</td>
                    <td>@item.En_Model</td>
                    <td>@item.UserId</td>

                    @*<td><div class="green-circle"></div> </td>
                        <td><img src="@item.MainImageUrl"><p> @Html.DisplayFor(model => item.Date) </p> </td>
                        <td>@Html.DisplayFor(model => item.Maker)</td>
                        <td>@Html.DisplayFor(model => item.Description)</td>
                        <td>@Html.DisplayFor(model => item.Location)</td>
                        <td>@Html.DisplayFor(model => item.Price)</td>
                        <td>@Html.DisplayFor(model => item.Year)</td>
                        <td>@Html.DisplayFor(model => item.Model)</td>
                        <td>@Html.DisplayFor(model => item.agentName)</td>*@
                    <td>
                        <ul class="sign-in">
                            <li class="nav-item dropdown inline-view pro-hover">
                                <p>
                                    <a class="nav-link dropdown-toggle nav-btn" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Manage Ads
                                    </a>
                                </p>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="#"><i class="fa fa-level-up"></i> Upgrade Listing</a>
                                    <a class="dropdown-item" href="@Url.Action("Update","Motors",new { AdId = item.Id})" id="btnEditAds"><i class="fa fa-pencil"></i> Edit Listing</a>
                                    <a class="dropdown-item" href="#"><i class="fa fa-youtube-play"></i> Video Tour Url</a>
                                    <a class="dropdown-item" href="#"><i class="fa fa-search"></i> View Ad</a>
                                    <a class="dropdown-item" href="#"><i class="fa fa-eye-slash"></i> Unpublish</a>
                                    <a class="dropdown-item" href="#"><i class="fa fa-times-circle-o"></i> Unavailable</a>
                                    <a class="dropdown-item" href="@Url.Action("Update","Motors",new { AdId = item.Id})"><i class="fa fa-trash"></i> Delete</a>
                                </div>
                            </li>
                        </ul>
                    </td>
                </tr>

            </table>

        </div>
    }


    b += 5;
    c++;
    itemsCount -= 5;
}


@{
    int pageCount = Model.Count;
}

@if (pageCount != 0)
{
    <div class="pagination" style="display:none">
        <a href="#"><i class="fa fa-chevron-left" aria-hidden="true"></i></a>
        @{
            var pagee = 1;
        }


        @while (pageCount > 0)
        {
            <a onclick="ShowPageItems(@pagee)">@pagee</a>

            pagee++;

            pageCount -= 5;
        }

        <a href="#"><i class="fa fa-chevron-right" aria-hidden="true"></i></a>
    </div>
}