insouq.Web/Controllers/AdsController.cs
using insouq.Services.IServices;
using insouq.Shared.DTOS;
using insouq.Shared.DTOS.Filters;
using insouq.Shared.Utility;
using insouq.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace insouq.Web.Controllers
{
    public class AdsController : Controller
    {
        private readonly ITypeService _typeService;
        private readonly IAdsService _adsService;
        private readonly IUsersService _usersService;
        private readonly ICategoryService _categoryService;
        private readonly INotificationsService _notificationsService;
        public AdsController(
            ITypeService typeService,
            IAdsService adsService,
            IUsersService usersService,
            ICategoryService categoryService,
            INotificationsService notificationsService)
        {
            _adsService = adsService;
            _typeService = typeService;
            _usersService = usersService;
            _categoryService = categoryService;
            _notificationsService = notificationsService;
        }

        private int getUserId()
        {
            try
            {
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var claims = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
                //if(claims != null )
                return Int32.Parse(claims.Value);
            }catch(ArgumentNullException e)
            {
                throw new Exception("User Is Not Logged In");
            }
        }

        public async Task<IActionResult> Categories(int typeId)
        {
            var cateogires = await _categoryService.GetByTypeId(typeId);

            ViewBag.TypeId = typeId;

            return View(cateogires);
        }


        public IActionResult PackagesSubsicription()
        {
            return View();
        }

        public async Task<IActionResult> PostAnAd()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }

            var typesDTO = await _typeService.GetAll();

            return View(typesDTO);
        }

        public async Task<IActionResult> Details(int adId, int typeId)
        {
            var ad = await _adsService.GetAd(adId, typeId);

            if(ad == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var IsProcessDone = 0;
            var IsInFav = false;
            var loggedInUserId = 0;

            if (User.Identity.IsAuthenticated)
            {
                loggedInUserId = getUserId();
                IsProcessDone = await _adsService.IsDeatilsProcessDone(loggedInUserId, typeId, adId, ad.CategoryId);
                IsInFav = await _adsService.IsInFavorite(loggedInUserId, adId);
            }

            var adDetailsVM = new AdDetailsVM
            {
                Ad = ad,
                User = await _usersService.GetById(ad.UserId),
                SimilarAds = await _adsService.GetSimilarAds(typeId, ad.CategoryId, adId),
                IsInFavorite =IsInFav,
                IsProcessDone = IsProcessDone

            };

            return View(adDetailsVM);
        }

        public async Task<IActionResult> All(int typeId, 
            int categoryId , string searchText ,string location,
            string maxKm, string minKm , string maxYear ,
            string minYear, string maxPrice , string minPrice,
            string maker,string model, string trim
            )
        {
            dynamic ads;

            var cateogryName = "";

            var categoryStatus = 0;
             
            if(categoryId == 0)
            {
                ads = await _adsService.GetAds(typeId, searchText, location, int.Parse(maxKm==null?"0": maxKm), int.Parse(minKm == null ? "0" : minKm), int.Parse(maxYear == null ? "0" : maxYear), int.Parse(minYear == null ? "0" : minYear), double.Parse(maxPrice == null ? "0" : maxPrice), double.Parse(minPrice == null ? "0" : minPrice), maker, model, trim);
            }
            else
            {
                ads = await _adsService.GetAdsByCategoryId(0,typeId, categoryId, searchText, location, int.Parse(maxKm == null ? "0" : maxKm), int.Parse(minKm == null ? "0" : minKm), int.Parse(maxYear == null ? "0" : maxYear), int.Parse(minYear == null ? "0" : minYear), double.Parse(maxPrice == null ? "0" : maxPrice), double.Parse(minPrice == null ? "0" : minPrice), maker, model, trim);


                var category = await _categoryService.GetById(categoryId);

                if (category != null)
                {
                    cateogryName = category.En_Name;
                    categoryStatus = category.Status;
                }
            }
            

            var allAdsVM = new AllAdsVM
            {
                Ads = ads,
                TypeId = typeId,
                CategoryId = categoryId,
                CategoryName = cateogryName,
                CategoryStatus = categoryStatus,
                SearchLocation = location,
            };

            return View(allAdsVM);
        }


        #region API_CALLS


        
        [HttpPost]
        public async Task<JsonResult> SaveFillters([FromBody] SaveFiltersDTO model)
        {

            try
            {


                int userId = getUserId();

                var response = await _adsService.SaveFillters(userId, model);

                return Json(response);
            }catch (Exception e)
            {
                return  Json(new { error= e.Message.ToString() });
            }
        }


        [HttpPost]
        public async Task<JsonResult> Delete([FromBody] DeleteAdDTO dto)
        {
            var response = await _adsService.DeleteAd(getUserId(), dto.AdId);

            return Json(response);
        }

        [HttpPost]
        public async Task<JsonResult> MakeAnOffer([FromBody] MakeAnOfferDTO model)
        {
            if (!ModelState.IsValid)
            {
                var errors = string.Join(Environment.NewLine,
                    ModelState.SelectMany(x => x.Value.Errors.Select(y => y.ErrorMessage)));

                return Json(new { isSuccess = false, message = errors });
            }

            var response = await _adsService.MakeAnOffer(getUserId(), model);

            return Json(response);
        }

        [HttpPost]
        public async Task<JsonResult> ReportAd([FromBody] ReportDTO model)
        {
            if (!ModelState.IsValid)
            {
                var errors = string.Join(Environment.NewLine,
                    ModelState.SelectMany(x => x.Value.Errors.Select(y => y.ErrorMessage)));

                return Json(new { isSuccess = false, message = errors });
            }

            var response = await _adsService.ReportAd(getUserId(), model);

            return Json(response);
        }

        [HttpPost]
        public async Task<JsonResult> AddToFavorite([FromBody] FavoriteAdDTO model)
        {
            if (!ModelState.IsValid)
            {
                var errors = string.Join(Environment.NewLine,
                    ModelState.SelectMany(x => x.Value.Errors.Select(y => y.ErrorMessage)));

                return Json(new { isSuccess = false, message = errors });
            }

            var response = await _adsService.AddToFavorite(getUserId(), model);

            return Json(response);
        }

        [HttpPost]
        public async Task<JsonResult> RemoveFromFavorite([FromBody] FavoriteAdDTO model)
        {
            if (!ModelState.IsValid)
            {
                var errors = string.Join(Environment.NewLine,
                    ModelState.SelectMany(x => x.Value.Errors.Select(y => y.ErrorMessage)));

                return Json(new { isSuccess = false, message = errors });
            }

            var response = await _adsService.RemoveFromFavorite(getUserId(), model);

            return Json(response);
        }

        [HttpPost]
        public async Task<JsonResult> ApplyForJob([FromForm] ApplyJobDTO model)
        {
            if (!ModelState.IsValid)
            {
                var errors = string.Join(Environment.NewLine,
                    ModelState.SelectMany(x => x.Value.Errors.Select(y => y.ErrorMessage)));

                return Json(new { isSuccess = false, message = errors });
            }

            var response = await _adsService.ApplyForJob(getUserId(), model);

            return Json(response);
        }

        [HttpGet]
        public async Task<PartialViewResult> GetMyAds(int typeId)
        {
            var ads = await _adsService.GetUserAds(getUserId(), typeId, true);

            return PartialView("~/Views/Partials/_MyAd.cshtml", ads);
        }

        [HttpGet]
        public async Task<PartialViewResult> GetUserAds(int userId, int typeId)
        {
            var ads = await _adsService.GetUserAds(userId, typeId, false);

            return PartialView("~/Views/Partials/_UserAd.cshtml", ads);
        }

        [HttpGet]
        public async Task<PartialViewResult> GetMyFavoriteAds(int typeId)
        {
            var ads = await _adsService.GetMyFavoriteAds(getUserId(), typeId);

            return PartialView("~/Views/Partials/_MyFavorite.cshtml", ads);
        }

        [HttpGet]
        public async Task<PartialViewResult> GetMySearches(int typeId)
        {
            var srearches = await _usersService.getSavedSearches(getUserId(), typeId);

            return PartialView("~/Views/Partials/_SavedSearchCards.cshtml", srearches);
        }

        [HttpGet]
        public async Task<JsonResult> NotiCont()
        {
            try
            {
                var UserId = getUserId();

                var response = _notificationsService.HasUnOpendNotifications(UserId);

insouq.Web/Views/Ads/Categories.cshtml
@using insouq.Shared.DTOS.CategoryDTOS
@using insouq.Shared.Utility
@model List<CategoryDTO>



<div class="row">
    <div class="col-md-2">
        <div class="bann-left-sub">
            <img onerror="this.src='/images/defaultAdImage.png'" src="~/assets/img/86.png" alt="">
        </div>
    </div>
    <div class="col-md-8 bann-marge">
        <div class="bann-top">

            <img onerror="this.src='/images/defaultAdImage.png'" src="~/assets/img/88.png" alt="">
        </div>


        <section class="section-padding">
            <div class="-card text-center wow  wow fadeInUp">
                <h1 class="section-title1">@StaticFunctions.GetTypeName(ViewBag.TypeId)</h1>
                <div class="row">
                    @foreach (var category in Model)
                    {
                        var color = StaticFunctions.GetColorByTypeId(ViewBag.TypeId);
                        <div class="col-md-4 items">
                            <span class="motors-color-1" style="background:@color;">@category.NumberOfAds</span>
                            <a asp-controller="Ads" asp-action="All" asp-route-typeId="@ViewBag.TypeId" asp-route-categoryId="@category.Id">
                                <div class="subcategory-box" style="border:1px solid @color;">
                                    <p><img onerror="this.src='/images/defaultAdImage.png'" style="height: 50px;" src="@category.FirstImage" alt=""><p>
                                    <p class="subcategory-p">@category.En_Name</p>
                                </div>
                            </a>
                        </div>
                    }
                </div>
            </div>
        </section>

    </div>
    <div class="col-md-2">
        <div class="bann-right-sub">
            <img onerror="this.src='/images/defaultAdImage.png'" src="~/assets/img/84.png" alt="">
        </div>
    </div>
</div>









<script type="text/javascript">
    $(Document).ready(() => {
        console.log("in location ");
        $.ajax({
            url: "/DropDowns/GetAllLocation",
            method: "GET",
            success: function (response) {
                $.each(response.items, function (i, item) {

                    $("#locationDL").append(`<option value='${item.en_Text} - ${item.ar_Text}'>${item.en_Text}</option>`);

                });
            },
            error: function (error) {
                alert(error.message);
            }
        });
    });
    var makerDLloaded = false;
    $("#makerDL").on("click", function () {
        if (makerDLloaded)
            return;
        $.ajax({
            url: "/DropDowns/GetAllMotorMaker",
            method: "GET",
            success: function (response) {
                $.each(response.items, function (i, item) {
                    $("#makerDL").append(`<option value='${item.en_Text} - ${item.ar_Text}'>${item.en_Text}</option>`);
                });
            },
            error: function (error) {
                alert(error.message);
            }
        });
        makerDLloaded = true;
    });
    $("#makerDL").on("change", function () {
        $('#modelDL option').remove();
        $("#modelDL").append(`<option value=''>All Models</option>`);
        $("#modelDL").val(null);
        var maker = $("#makerDL").val();
        $.ajax({
            url: `/DropDowns/GetAllMotorModelByMaker?maker=${maker}`,
            method: "GET",
            success: function (response) {
                $.each(response.items, function (i, item) {
                    $("#modelDL").append(`<option value='${item.en_Text} - ${item.ar_Text}'>${item.en_Text}</option>`);
                });
            },
            error: function (error) {
                alert(error.message);
            }
        });
    });
    $("#modelDL").on("change", function () {
        $("#trimDL").val(null);
        var model = $("#modelDL").val();
        $.ajax({
            url: `/DropDowns/GetAllMotorTrimByModel?model=${model}`,
            method: "GET",
            success: function (response) {
                $.each(response.items, function (i, item) {
                    $("#trimDL").append(`<option value='${item.en_Text} - ${item.ar_Text}'>${item.en_Text}</option>`);
                });
            },
            error: function (error) {
                alert(error.message);
            }
        });
    });
    $("#cat1").on("change", function () {
        console.log("cat dddd");
        var cat = $("#cat1").val();
        console.log("cat 1 =", cat);
        if (cat == 2 || cat == 8) {
            $("#moreFilters").fadeIn()
        } else {
            $("#moreFilters").fadeOut()
        }
    });
    function toggleMore() {
        console.log("toggleMore")
    }

insouq.Web/Views/Ads/PackagesSubsicription.cshtml
<div class="notification-style">

    <!--<div class="container">-->
    <!-- Trigger the modal with a button -->
    <!-- Modal -->
    <!--<div class="modal fade" id="myModal22" role="dialog">
        <div class="modal-dialog dialog-padding">-->
    <!-- Modal content-->
    <!--<div class="modal5-styles">
                    <div class="modal-header-styles2">
                        <h4 class=" mar-pop">Select a package that works for you</h4>
                        <button type="button" class="close-style7" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <div class="padding-form check-po">
                            <p class="free-po">Free</p>
                            <label class="cont2">
                                <p class="text-style3">Hide my name and photo on my ads</p>
                                <input type="checkbox">
                                <span class="checkmark5"></span>
                                <p>Normal Visibility</p>
                            </label>
                        </div>
                        <h4 class="mar-pop">Upgrade Your Standard ad into a featured one</h4>
                        <p class="mar-pop">featured ads are placed on top of all Standard ads</p>
                        <div class="padding-form check-po">
                            <p class="free-po"> AED 19</p>
                            <label class="cont2">
                                <p class="text-style3">Featured Your ad for 3 days+</p>
                                <input type="checkbox">
                                <span class="checkmark5"></span>
                                <p>Get 6x more offers</p>
                            </label>
                        </div>
                        <div class="padding-form check-po">
                            <p class="free-po"> AED 29</p>
                            <label class="cont2">
                                <p class="text-style3">Featured Your ad for 7 days+</p>
                                <input type="checkbox">
                                <span class="checkmark5"></span>
                                <p>Get 10x more offers</p>
                            </label>
                        </div>
                        <div class="padding-form check-po">
                            <p class="free-po">AED 44</p>
                            <label class="cont2">
                                <p class="text-style3">Featured Your ad for 14 days+ </p>
                                <input type="checkbox">
                                <span class="checkmark5"></span>
                                <p>Get 15x more offers</p>
                            </label>
                        </div>
                        <form class="" action="" method="post">
                            <button type="button" class="signin-btn5" data-dismiss="modal" name="button" data-toggle="modal" data-target="#myModal23">Yes, I Agree </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>-->
    <div class="container">
        <!-- Trigger the modal with a button -->
        <!-- Modal -->
        <div class="modal fade" id="myModal22" role="dialog">
            <div class="modal-dialog dialog-padding">
                <!-- Modal content-->
                <div class="modal5-styles">
                    <div class="modal-header-styles2">
                        <h4 class=" mar-pop">Select a package that works for you</h4>
                        <button type="button" class="close-style7" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <div class="padding-form check-po">
                            <p class="free-po">Free</p>
                            <label class="cont2 backeg-fix">
                                <p class="backeg-style-text">Keep your ad free</p>
                                <input type="checkbox">
                                <span class="checkmark5"></span>
                            </label>
                        </div>
                        <h4 class="mar-pop">Upgrade Your Standard ad into a featured one</h4>
                        <p class="mar-pop font-package">featured ads are placed on top of all Standard ads</p>
                        <div class="padding-form check-po">
                            <p class="free-po"> AED 19</p>
                            <label class="cont2 backeg-fix">
                                <p class="backeg-style-text">Featured Your ad for 3 days</p>
                                <input type="checkbox">
                                <span class="checkmark5"></span>
                            </label>
                        </div>
                        <div class="padding-form check-po">
                            <p class="free-po"> AED 29</p>
                            <label class="cont2 backeg-fix">
                                <p class="backeg-style-text">Featured Your ad for 7 days</p>
                                <input type="checkbox">
                                <span class="checkmark5"></span>
                            </label>
                        </div>
                        <div class="padding-form check-po">
                            <p class="free-po">AED 44</p>
                            <label class="cont2 backeg-fix">
                                <p class="backeg-style-text">Featured Your ad for 14 days </p>
                                <input type="checkbox">
                                <span class="checkmark5"></span>
                            </label>
                        </div>
                        <form class="" action="" method="post">
                            <button type="button" class="signin-btn5" data-dismiss="modal" name="button" data-toggle="modal" data-target="#myModal23">Yes, I Agree </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <!-- Trigger the modal with a button -->
        <!-- Modal -->
        <div class="modal fade" id="myModal23" role="dialog">
            <div class="modal-dialog dialog-padding">
                <!-- Modal content-->
                <div class="modal5-styles">
                    <div class="modal-header-styles2">

                        <button type="button" class="close-style7" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <div class="par-style">
                            <img onerror="this.src='/images/defaultAdImage.png'" class="takes-img" src="~/assets/img/92.png" alt="">
                            <h4 class="emailme">Your ad was submitted and is under review</h4>
                            <p class="takes-p">Don't worry this usually takes 1-5 minutes We'll notify you when your ad is live.</p>
                        </div>
                        <form class="" action="" method="post">
                            <button type="button" class="signin-btn5" data-dismiss="modal" name="button" onclick="window.location.href='/Home/Index'">Done</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="fade active show containers trending-cat">


        <!-- Tab content -->
        <div class="tab-content tabs-content-style" style="text-align: center;width: 100%; margin-left:0px;">

            <h2>Safty First!</h2>



            <div class="term-p">


                <p> we review all ads to keep everyone on insouq safe amd happy</p>
                <p>1. for any prohitabited or activity that violates UAE law </p>
                <p>2. in the wrong category</p>
                <p>3.placed multiple times, or in multiple categories</p>
                <p>4. wiyh fradulent or misleading information</p>
                <p>5. for an item that is located outside UAE</p>
                <p>
                    for more information read our
                    <br><a asp-controller="Home" asp-action="Terms">terms and conditions</a>
                </p>
            </div>
            <button type="button" name="button" data-toggle="modal" data-target="#myModal22">yes, i agree!</button>
        </div>
    </div>
</div>